### ISSUE TITLE
[FEATURE] Add a little more eloborations on which clang-tidy checks going to used.

### ISSUE THREAD

**Issue by p1v0t** [filipdutescu/modern-cpp-template#18]
[clang-tidy](https://clang.llvm.org/extra/clang-tidy) has [set of checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html) and putted under the some [flags](https://clang.llvm.org/extra/clang-tidy). I think it's better to be explicit about which checks are available. I think it's better to list them in the corresponding CMake module of the template, StaticAnalyzers.cmake.

I make a commit, which available in here: https://github.com/p1v0t/modern-cpp-template/commit/f64f3d3ec76078f8200ac5c794c5e80661a71da3 

I can pull it, if you people are see whether its useful or not.

**Comment by filipdutescu** [comment]
This sounds like a really good idea. Will look a bit more into the checks and flags provided by `clang-tidy` and I will try to find a proper way to make it a bit more obvious what checks are available. Thanks for the commit as well, it was very nice to include an example of what you wish for.

**Comment by filipdutescu** [comment]
On a second look, I will not implement your desired changes, as those options should be defined in the [`.clang-tidy` file](https://github.com/filipdutescu/modern-cpp-template/blob/master/.clang-tidy), rather then in CMake (at least in my vision). If you feel like it makes more sense to have them defined in CMake, please let me know why, so we can discuss your reasoning.
