### ISSUE TITLE
[BUG] make install fail

### ISSUE THREAD

**Issue by HungMingWu** [filipdutescu/modern-cpp-template#2]
**Describe the bug**
make install,failed

**To Reproduce**
make install

**Desktop (please complete the following information):**
 - Ubuntu 18.04

**Additional context**
include/${PROJECT_NAME} doesn't exist, the correct include path is include/tmp
So make install would failed

**Comment by filipdutescu** [comment]
@HungMingWu, I am sorry for the inconvenience. The template has now been updated and the bug should be fixed. Thank you for reporting it, all help received is very appreciated! 

Would you be so kind as to confirm with the me issue is now fixed, please? Thank you in advance.

**Comment by HungMingWu** [comment]
@filipdutescu  the install issue is fixed.
