### ISSUE TITLE
How to make compilation warnings not work for third party libraries?

### ISSUE THREAD

**Issue by stoneboy100200** [filipdutescu/modern-cpp-template#20]
Threr are many third party libraries in my project, I just let compilation warnings to work for my code，not work for third party libraries. Could you please tell me what should I do?

**Comment by filipdutescu** [comment]
So you also want the warnings to apply on the 3rd party libs, right? They should be enabled by default. I see them when using OpenCV, for example.

I will need more details in order to try and help you out, such as OS, compiler and version, if the libs are C++ native or not, static or DLLs etc.

But you should see any warnings that might appear when building with CMake.

**Comment by stoneboy100200** [comment]
You misunderstand me. I don't want the warning to apply on the 3rd party libs. 
My env as the follows:
OS: Linux or QNX
GCC: 9.3.0
Platform: x86_64 or aarch64

Could you please help me to disable the warning to apply on the 3rd party libs. Just apply on my src code.

**Comment by filipdutescu** [comment]
On another project I just defined some macros to help me ignore warnings I did not want to see in OpenCV

```cpp
#define UAVPC_PRAGMA(x) _Pragma(#x) #ifdef __clang__ #define UAVPC_DISABLE_WARNING(x) \ UAVPC_PRAGMA(clang diagnostic push) \ UAVPC_PRAGMA(clang diagnostic ignored x) #define UAVPC_END_DISABLE_WARNING UAVPC_PRAGMA(clang diagnostic pop) #elif __GNUC__ #define UAVPC_DISABLE_WARNING(x) UAVPC_PRAGMA(GCC diagnostic ignored x) #define UAVPC_END_DISABLE_WARNING UAVPC_PRAGMA(GCC diagnostic pop) #endif #define UAVPC_OPENCV_DISABLE_WARNINGS \ UAVPC_DISABLE_WARNING("-Wconversion") \ UAVPC_DISABLE_WARNING("-Wold-style-cast") \ UAVPC_DISABLE_WARNING("-Wsign-conversion") \ UAVPC_DISABLE_WARNING("-Wuseless-cast") #define UAVPC_END_OPENCV_DISABLE_WARNINGS \ UAVPC_END_DISABLE_WARNING \ UAVPC_END_DISABLE_WARNING \ UAVPC_END_DISABLE_WARNING \ UAVPC_END_DISABLE_WARNING 
```

Which I would then use like so:

```cpp
#include "CompatibilityMacros.hpp"

UAVPC_OPENCV_DISABLE_WARNINGS #include <opencv2/videoio.hpp> UAVPC_END_OPENCV_DISABLE_WARNINGS
```

This is the best solution I could find. Hopefully it helps you as well.

**Comment by stoneboy100200** [comment]
Thanks for your suggestion. So I have to wrap every header files for 3rd party, it seems too much trouble :)

**Comment by filipdutescu** [comment]
I think you can disable all warnings at once, depending on your compiler, so you could look into that as well.

**Comment by stoneboy100200** [comment]
I found the key word "SYSTEM" could avoid compile warning.
target_include_directories(${PROJECT_NAME} SYSTEM INTERFACE ${PROJECT_SOURCE_DIR}/include）
