### ISSUE TITLE
How to properly add multiple source and header files in clang-format target? [FEATURE]

### ISSUE THREAD

**Issue by dadep88** [filipdutescu/modern-cpp-template#21]
Adding new files in SourcesAndHeaders.cmake clang-format target stop working, giving "No such file or directory".
It seems only one file can be define for both sources and headers cmake variables.

**Comment by filipdutescu** [comment]
Thank you for reporting this bug! I am working on a fix, which will be included in the next release of the template! Sorry for the inconvenience caused, in the meantime.
