### ISSUE TITLE
[BUG] Github Actions doesn't work + Solution

### ISSUE THREAD

**Issue by UTFeight** [filipdutescu/modern-cpp-template#44]
**Describe the bug**
Some of the github actions are outdated.

**To Reproduce**
Look at the last commit

**Desktop:**

* OS: Linux (Arch btw.)
* Version: 6.4.4-arch1-1

**Comment by UTFeight** [comment]
I have forked to project to extend It's functionality. While doing so I have fixed some of the github action problems + addressing some platform dependent `GTest` issues.

take a look at [my fork](https://github.com/UTFeight/Cpp-Cmake-Template) to learn more about it.

I could create a PR in the future

**Comment by alexfreudenberg** [comment]
In the spirit of your bio, I think it is fair to say that "Nicht alle Helden tragen Kappen"!
