### ISSUE TITLE
[FEATURE] Add Dockerfile

### ISSUE THREAD

**Issue by Zethson** [filipdutescu/modern-cpp-template#6]
**Is your feature request related to a problem? Please describe.**
Some people may not have all the required libraries/compilers to compile the project.
However, they may have a container engine available.

**Describe the solution you'd like**
Add a Dockerfile that allows for simple compilation.

**Additional context**
https://docs.conan.io/en/latest/howtos/run_conan_in_docker.html

**Comment by filipdutescu** [comment]
> Some people may not have all the required libraries/compilers to compile the project.

Like the idea of a "portable" sandbox that people can use to test all features of the project! Truth be told, I don't even have everything I provided (i.e. haven't tested `Catch2` unit testing, since the only difference from `GoogleTest` would be the code in the source).
