### ISSUE TITLE
[SUGGESTION] Improve spelling and description of ccache

### ISSUE THREAD

**Issue by jrosdahl** [filipdutescu/modern-cpp-template#7]
The preferred spelling of ccache is “Ccache” or “ccache”, so I suggest using the former variant. Also, I think that it would be better to say “speed up **rebuild** time” instead of “speed up **build** time” since that’s more accurate.

**Comment by filipdutescu** [comment]
@jrosdahl thank you very much for both your suggestion and the PR! I appreciate the time you took to contribute to my template and I want to include your suggestion!
