### ISSUE TITLE
[BUG] Workflow syntax error on build action from PR #5

### ISSUE THREAD

**Issue by filipdutescu** [filipdutescu/modern-cpp-template#9]
**Describe the bug**
In the file merged from [#5](https://github.com/filipdutescu/modern-cpp-template/pull/5), according to GitHub, `INSTALL_LOCATION: "d:/a/.local",` is invalid YAML syntax:

> **Invalid workflow file**
>
>You have an error in your yaml syntax on line 26.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [GitHub Actions](https://github.com/filipdutescu/modern-cpp-template/actions),
2. Click on `.github/workflows/build.yml`,
3. On the center-right panel, click on `Merge pull request #5 from thebino/Feature/PipelineRefactor`,
4. Scroll down to line 26 to see the error.

**Expected behavior**
The workflow is expected to run (on the creation of a tag) and create a release with artefacts from the build results.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Rather than a PC, the following refers to the GitHub Actions' container:
* OS: Windows
* Version: Latest

**Additional context**
* Environment script: `C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat`
* Compiler: MSVC

**Comment by Zethson** [comment]
```
YAMLException: missed comma between flow collection entries at line 27, column 30:
                CACHE_LOCATION: ${{env.INSTALL_LOCATION}},
```
